runtime: python39
entrypoint: gunicorn -b :$PORT app:app

env_variables:
    MAPBOX_ACCESS_TOKEN: 'YOUR_MAPBOX_ACCESS_TOKEN_HERE'
    SECRET_KEY: 'abc'

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto
