runtime: python39
entrypoint: gunicorn -b :$PORT app:app

instance_class: B2  # Upgraded instance class for increased memory limits

env_variables:
  MAPBOX_ACCESS_TOKEN: 'YOUR_MAPBOX_ACCESS_TOKEN_HERE'
  SECRET_KEY: 'abc'

handlers:
  - url: /static
    static_dir: static/
  - url: /.*
    script: auto

basic_scaling:
  max_instances: 5
  idle_timeout: 10m  # Instances are shut down if idle for this duration
